version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - sspage_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - sspage_static:/data/static/
      - sspage_media:/data/media/

  django:
    image: sspage:04
    networks:
      - sspage_network
    volumes:
      - sspage_media:/home/django/media
      - sspage_static:/home/django/staticfiles

  mariadb:
    image: mariadb:10.5
    networks:
      - sspage_network
    volumes:
      - sspage_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password

networks:
  sspage_network:

volumes:
  sspage_static:
  sspage_media:
  sspage_mariadb: